import Foundation

#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

/// Formats annotations as structured markdown and copies to the system pasteboard.
///
/// The output format is designed to be pasted directly into a Claude Code session
/// so the AI can identify exactly which UI elements need changes and what to do.
public enum MarkdownExporter {

    // MARK: - Public

    /// Format all annotations as a markdown document and copy to clipboard.
    /// Returns the generated markdown string.
    @discardableResult
    public static func copyToClipboard(
        annotations: [Annotation],
        screenName: String = "Screen"
    ) -> String {
        let markdown = format(annotations: annotations, screenName: screenName)
        copyString(markdown)
        return markdown
    }

    /// Format annotations as structured markdown without copying.
    public static func format(
        annotations: [Annotation],
        screenName: String = "Screen"
    ) -> String {
        guard !annotations.isEmpty else {
            return "# No annotations captured."
        }

        let timestamp = ISO8601DateFormatter().string(from: Date())
        var lines: [String] = []

        lines.append("# SwiftUI Annotations — \(screenName)")
        lines.append("Generated by AnnotationOverlay")
        lines.append(timestamp)
        lines.append("")

        for annotation in annotations {
            lines.append(formatAnnotation(annotation))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    /// Export annotations as a JSON array (for future MCP integration).
    public static func exportJSON(annotations: [Annotation]) -> String {
        let entries = annotations.map { a -> String in
            let m = a.metadata
            let escaped = a.note.replacingOccurrences(of: "\"", with: "\\\"")
            return """
              {
                "number": \(a.number),
                "element": "\(m.viewType)",
                "accessibilityID": \(jsonString(m.accessibilityIdentifier)),
                "accessibilityLabel": \(jsonString(m.accessibilityLabel)),
                "frame": { "x": \(Int(m.windowFrame.origin.x)), "y": \(Int(m.windowFrame.origin.y)), "width": \(Int(m.windowFrame.width)), "height": \(Int(m.windowFrame.height)) },
                "viewPath": "\(m.viewPath)",
                "note": "\(escaped)",
                "rawClass": "\(m.rawClassName)"
              }
            """
        }

        return "[\n\(entries.joined(separator: ",\n"))\n]"
    }

    // MARK: - Clipboard

    /// Copy a string to the platform pasteboard.
    public static func copyString(_ string: String) {
        #if canImport(UIKit)
        UIPasteboard.general.string = string
        #elseif canImport(AppKit)
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(string, forType: .string)
        #endif
    }

    // MARK: - Private

    private static func formatAnnotation(_ annotation: Annotation) -> String {
        let m = annotation.metadata
        var lines: [String] = []

        lines.append("## Annotation \(annotation.number)")
        lines.append("- **Element:** \(m.viewType)")

        if let id = m.accessibilityIdentifier {
            lines.append("- **Accessibility ID:** `\(id)`")
        }
        if let label = m.accessibilityLabel {
            lines.append("- **Accessibility Label:** \"\(label)\"")
        }

        let traits = m.traitsDescription
        if traits != "none" {
            lines.append("- **Traits:** \(traits)")
        }

        lines.append("- **Frame:** x: \(Int(m.windowFrame.origin.x)), y: \(Int(m.windowFrame.origin.y)), width: \(Int(m.windowFrame.width)), height: \(Int(m.windowFrame.height))")
        lines.append("- **View Path:** \(m.viewPath)")
        lines.append("- **Raw Class:** `\(m.rawClassName)`")

        if !annotation.note.isEmpty {
            lines.append("- **Note:** \"\(annotation.note)\"")
        }

        return lines.joined(separator: "\n")
    }

    private static func jsonString(_ value: String?) -> String {
        guard let v = value else { return "null" }
        return "\"\(v.replacingOccurrences(of: "\"", with: "\\\""))\""
    }
}
